services:
  app:
    image: ${REGISTRY:-docker.io/napat}/my-go-app:${VERSION:-latest}
    platform: ${PLATFORM:-linux/arm64} # You can override this with amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
